version: '3.8'

services:
  nestapp:
    build: ./
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - '5433:5432'

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '5050:80'

volumes:
  pgdata:
